### ISSUE TITLE
Onvif probe is bound to the default interface

### ISSUE THREAD

**Issue by kfirsa** [ZoneMinder/zoneminder#1653]
Although the system has two interfaces the multicast probe (239.255.255.250:3702) is bound to the one having a default route.

My design is as follows:<ISP>--(R)---LAN--(ZM)---[CAM network]

verified with tcpdump.
accessing onvif profile based on ip works but the probe failed.

**Comment by JoeAlamo** [comment]
I have also recently experienced this issue.

I am not aware of a code based fix (I'm sure that when setting up the UDP Multicast socket you should be able to join all available interfaces).

However, there is a temporary network level fix. Create a static route for traffic to 239.255.255.250/32 to go via your LAN/CAM interface.

This worked for me, I know it's not great.

**Comment by ziotibia81** [comment]
I did some research. I'm not a multicast expert but seems that linux need a static route to multicast address for each interface that need multicast traffic. Windows does it for default.

more info here: [https://askubuntu.com/questions/501842/add-multicast-ip-address-into-kernel-route-table](https://askubuntu.com/questions/501842/add-multicast-ip-address-into-kernel-route-table)

**Comment by klausseufzger** [comment]
I am running zoneminder 1.32.2 on Ubuntu 18.04.01 in a virtual machine with two interface (one home and one camera network). I also had the problem with ONVIF detection.

Adding a static route for 239.255.255.250 worked for me. Use the command 
`route add -net 239.255.255.250 netmask 255.255.255.255 eth1`
where eth1 is the interface of your camera network.

If you use a newer ubuntu version with netplan you can also add it the route to the interface. This is my netplan config:

```
network:
    ethernets:
#home network
        eth0:
            addresses: []
            dhcp4: true
#camera network
        eth1:
            addresses: [192.168.1.5/24]
            routes:
              - to: 239.255.255.250/32
                via: 192.168.1.5
            dhcp4: no
    version: 2
```
