### ISSUE TITLE
'zma -m 2' exited abnormally, exit status 255

### ISSUE THREAD

**Issue by arthur798** [ZoneMinder/zoneminder#2925]
Hiya I have this config, i know this is not exactly zoneminder official image but it's close enough

```
  zoneminder:
    image: quantumobject/docker-zoneminder:1.34
#    image: adc3c7a0ca0a
    container_name: zoneminder
    restart: unless-stopped
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - "$ZONEMINDER_HTTP_PORT:80"
#      - "$ZONEMINDER_HTTPS_PORT:443"
      - "9567:9000" # Event Notification Port
    privileged: true
    shm_size: 4096m
    volumes:
      - /var/empty
      - $USERDIR/docker/shared:/shared
      - $USERDIR/docker/zoneminder/backups:/var/backups
      - $USERDIR/docker/zoneminder:/var/cache/zoneminder
      - $USERDIR/docker/zoneminder/config:/config
      - type: tmpfs
        target: /dev/shm
    environment:
      SHMEM: "50%"
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PHP_TZ: $TZ
      ZM_DB_HOST: $DB_HOST
      ZM_DB_PORT: $DB_PORT
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_ROOT: $USER
```
also I am getting

Got empty memory map file size 0, is the zmc process for this monitor running?

what could be the issue?
