### ISSUE TITLE
Reverse proxy configuration with Traefik2

### ISSUE THREAD

**Issue by MacGyver27** [ZoneMinder/zoneminder#3302]
Hello,

I am having quite troubles with configuring reverse proxy for Zoenminder (v1.36.4).

I am using `addPrefix` to add `/zm/` in background so user can directly access Zoneminder on its subdomain cam.example.com. This partially works - I am getting the web page, but some styles are missing and stream is not working. After some time I get redirected to `cam.example.com/zm/index.php` - which does not exist on subdomain context.. If I tries to load `cam.example.com/index.php` it succeeds.

### Direct access:
![image](https://user-images.githubusercontent.com/6546231/122842303-6223bc00-d2fd-11eb-9df8-2d9d195cda6e.png)

vs

### Subdomain access:
![image](https://user-images.githubusercontent.com/6546231/122842276-4fa98280-d2fd-11eb-8fe0-0f0c5945be4f.png)

### For the streams its the same scenario:
![image](https://user-images.githubusercontent.com/6546231/122842220-34d70e00-d2fd-11eb-8176-c74252edbf91.png)

Traefik2 configuration for the reverse proxy zoneminder:
```yml
http:

  routers:
    zoneminder.example.com:
      priority: 1
      entryPoints:
        - websecure
      rule: Host(`cam.example.com`)
      service: zoneminder.example.com
      middlewares:
        - zoneminder.example.com+addPrefix
        #- zoneminder.example.com+replacePathRegex

  services:
    zoneminder.example.com:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: 'http://192.168.255.12:50191'

  middlewares:
    zoneminder.example.com+redirectRegex:
      redirectRegex:
        regex: "^https?://cam.example.com/(.*)"
        replacement: "https://cam.example.com/zm/"
        permanent: true
    zoneminder.example.com+addPrefix:
      addPrefix:
        prefix: /zm
    zoneminder.example.com+replacePathRegex:
      replacePathRegex:
        regex: "/zm/index(.+)"
        replacement: "/index$1"
```

Any directions will be appreciated. Thanks, Michal
